name: check commits

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: run lint, build and test
        run: yarn install && yarn ci
